version: "3.7"

services:
  go:
    build: .
    container_name: app
    volumes:
      - ".:/go/src:cached"
    ports:
      - "8000:8000"
    depends_on:
      - "mongo"

  mongo:
    image: "mongo:4.2.6-bionic"
    container_name: mongo
    volumes:
      - ./db:/db
    ports:
      - "27017:27017"
    restart: always

  mongo_express:
    image: mongo-express
    container_name: mongo_express
    ports:
      - "8001:8001"
    depends_on:
      - "mongo"
    restart: always
