version: "3.7"

volumes:
  mongodb-volume:
    driver: local

services:
  go:
    build: ./server
    container_name: go-server
    volumes:
      - "./server:/go/src:cached"
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
    depends_on:
      - "mongo"

  mongo:
    image: "mongo:4.2.6-bionic"
    container_name: mongo
    volumes:
      - mongodb-volume:/data/db
    ports:
      - "27017:27017"
    restart: always

  mongo_express:
    image: mongo-express
    container_name: mongo_express
    ports:
      - "8081:8081"
    depends_on:
      - "mongo"
    restart: always
